### ISSUE TITLE
Why is start > 0?

### ISSUE THREAD

**Issue by aishmit** [mcupak/beacon-client#5]
Hey I was going through the code for BeaconClientImpl and noticed that you check to see if start > 0. From what I know, if the start parameter is 0-based should it not be inclusive? Thus start >= 0?

https://github.com/mcupak/beacon-client/blob/9d72cc14fd232e5ed65f756044ffb3995205db5e/beacon-client-impl/src/main/java/com.dnastack.beacon.client/BeaconClientImpl.java#L69

Thanks

**Comment by mcupak** [comment]
Nice catch! Fixed in develop.
